'use server';
/**
 * @fileOverview This flow is the main PriceNova AI Orchestrator.
 * It uses Gemini to provide realistic market data, group identical products,
 * and generate shopping advice in a single efficient server-side call.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const ProductSchema = z.object({
  platform: z.string().describe('The platform name (e.g. Amazon, Flipkart, Myntra, Ajio)'),
  title: z.string().describe('The full title of the product including brand and model'),
  description: z.string().describe('A brief realistic product description'),
  price: z.coerce.number().describe('The raw price as a number in INR'),
  productUrl: z.string().describe('A realistic URL to the product'),
  imageUrl: z.string().optional().describe('A realistic image URL'),
  specifications: z.string().optional().describe('Key specs of the product'),
});

const MatchedGroupSchema = z.object({
  groupId: z.string(),
  products: z.array(ProductSchema),
});

const OrchestratorOutputSchema = z.object({
  matchedGroups: z.array(MatchedGroupSchema).describe('Products grouped by identity (e.g. same model/variant).'),
  savingsAdvice: z.object({
    recommendationSummary: z.string(),
    bestOfferPlatform: z.string(),
    bestOfferProductTitle: z.string(),
    reasoning: z.string(),
  }).optional(),
});

export type OrchestratorOutput = z.infer<typeof OrchestratorOutputSchema>;

const orchestratorPrompt = ai.definePrompt({
  name: 'orchestratorPrompt',
  model: 'googleai/gemini-1.5-flash',
  input: { schema: z.object({ query: z.string() }) },
  output: { schema: OrchestratorOutputSchema },
  config: {
    temperature: 0.4,
  },
  prompt: `You are the PriceNova AI Market Intelligence Orchestrator. Your task is to provide realistic, current market data for: "{{query}}".

INSTRUCTIONS:
1. MARKET SIMULATION: Generate 15-20 highly realistic product listings as they would appear TODAY on major Indian platforms (Amazon, Flipkart, Myntra, Ajio, Croma, Nykaa, Meesho).
   - Use ACTUAL brands (e.g. for phones: Apple, Samsung; for pens: Reynolds, Parker, Pilot; for shoes: Nike, Adidas).
   - Include specific model names and variants.

2. RIGOROUS REALISTIC PRICING (INR):
   - Everyday Stationery (Pens/Pencils): ₹10 - ₹200 for single units or packs.
   - Standard Electronics: ₹5,000 - ₹50,000.
   - Flagship Mobiles/Laptops: ₹60,000 - ₹1,80,000.
   - Fashion/Sneakers: ₹500 - ₹12,000.
   - Grocery items: ₹20 - ₹800.
   - Luxury Items: Up to ₹5,00,000.
   - MATCH THE PRICE TO THE CATEGORY. A pen should NOT cost thousands of rupees unless it is a luxury Montblanc.

3. MATCH & GROUP: Analyze the simulated listings and group identical items (same brand, model, and variant) into matchedGroups.

4. SHOPPING ADVICE: Identify the best overall deal among all the generated listings.

IMPORTANT: Ensure the 'price' field is a raw number. Generate at least 15 unique product entries across multiple groups.`,
});

const priceNovaOrchestratorFlow = ai.defineFlow(
  {
    name: 'priceNovaOrchestratorFlow',
    inputSchema: z.object({ query: z.string() }),
    outputSchema: OrchestratorOutputSchema,
  },
  async (input) => {
    try {
      const { output } = await orchestratorPrompt(input);
      if (!output || !output.matchedGroups || output.matchedGroups.length === 0) {
        throw new Error('Incomplete data generated by AI');
      }
      return output;
    } catch (error: any) {
      console.error('Orchestrator Error:', error);
      
      const q = input.query.toLowerCase();
      let fallbackPrice = 499;
      let fallbackTitle = `${input.query} - Standard Edition`;

      if (q.includes('pen') || q.includes('pencil') || q.includes('stationery')) {
        fallbackPrice = 45;
        fallbackTitle = `Reynolds Jetter Classic Ball Pen - Pack of 5`;
      } else if (q.includes('phone') || q.includes('iphone') || q.includes('mobile') || q.includes('laptop')) {
        fallbackPrice = 54999;
        fallbackTitle = `${input.query} (128GB Storage)`;
      }

      const platforms = ['Amazon', 'Flipkart', 'Myntra', 'Ajio', 'Croma', 'Nykaa', 'Meesho'];
      const results: OrchestratorOutput = {
        matchedGroups: [
          {
            groupId: 'group-1',
            products: platforms.map((p, i) => ({
              platform: p,
              title: fallbackTitle,
              description: `Top rated ${input.query} on ${p}.`,
              price: Math.round(fallbackPrice * (1 + (i - 3) * 0.02)),
              productUrl: `https://${p.toLowerCase()}.com`,
              specifications: 'Standard quality'
            }))
          }
        ],
        savingsAdvice: {
          recommendationSummary: "Marketplace offers found.",
          bestOfferPlatform: "Flipkart",
          bestOfferProductTitle: fallbackTitle,
          reasoning: "Best current price for this standard model."
        }
      };

      return results;
    }
  }
);

export async function searchProductNova(query: string): Promise<OrchestratorOutput> {
  return priceNovaOrchestratorFlow({ query });
}
