'use server';
/**
 * @fileOverview This flow is the main PriceNova Orchestrator.
 * It uses Gemini to provide realistic market data, group identical products,
 * and generate shopping advice in a single efficient server-side call.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const ProductSchema = z.object({
  platform: z.string().describe('The platform name (e.g. Amazon, Flipkart)'),
  title: z.string().describe('The full title of the product'),
  description: z.string().describe('A brief realistic description'),
  price: z.coerce.number().describe('The raw price as a number'),
  productUrl: z.string().describe('A realistic URL to the product'),
  imageUrl: z.string().optional().describe('A realistic image URL'),
  specifications: z.string().optional().describe('Key specs of the product'),
});

const MatchedGroupSchema = z.object({
  groupId: z.string(),
  products: z.array(ProductSchema),
});

const OrchestratorOutputSchema = z.object({
  matchedGroups: z.array(MatchedGroupSchema).describe('Products grouped by identity (e.g. same model/variant).'),
  savingsAdvice: z.object({
    recommendationSummary: z.string(),
    bestOfferPlatform: z.string(),
    bestOfferProductTitle: z.string(),
    reasoning: z.string(),
  }).optional(),
});

export type OrchestratorOutput = z.infer<typeof OrchestratorOutputSchema>;

const orchestratorPrompt = ai.definePrompt({
  name: 'orchestratorPrompt',
  model: 'googleai/gemini-1.5-flash',
  input: { schema: z.object({ query: z.string() }) },
  output: { schema: OrchestratorOutputSchema },
  config: {
    temperature: 0.4,
  },
  prompt: `You are the PriceNova AI Search Orchestrator. Your task is to provide realistic, current market data for the product: "{{query}}".

INSTRUCTIONS:
1. SIMULATE SEARCH: Generate 6-10 realistic product listings as they would appear TODAY on major Indian platforms (Amazon, Flipkart, Myntra, Ajio, Croma, Nykaa, Meesho). 
   - Even for simple items like a "pen" or "notebook", provide realistic brand names (e.g. Parker, Reynolds, Classmate).
   - Prices MUST be realistic. Use the actual current market rate in INR for the product category.
   - For simple items, the price should be small (e.g., 50-100 INR). For premium electronics, it should be high (e.g., 70,000 INR).

2. MATCH & GROUP: Analyze the simulated listings and group identical items together. 
   - Identical items MUST have the same model, size, or specific variant.
   - Products with different variants (e.g. Blue vs Black ink, 128GB vs 256GB) MUST be in separate groups.

3. SHOPPING ADVICE: Analyze the results and identify the best overall deal based on price and platform reliability.

IMPORTANT: Ensure the 'price' field is a raw number without currency symbols or commas.`,
});

const priceNovaOrchestratorFlow = ai.defineFlow(
  {
    name: 'priceNovaOrchestratorFlow',
    inputSchema: z.object({ query: z.string() }),
    outputSchema: OrchestratorOutputSchema,
  },
  async (input) => {
    try {
      const { output } = await orchestratorPrompt(input);
      if (!output || !output.matchedGroups || output.matchedGroups.length === 0) {
        throw new Error('Incomplete data generated by AI');
      }
      return output;
    } catch (error: any) {
      console.error('Orchestrator Error:', error);
      // Return a structured fallback to keep the UI functional
      return {
        matchedGroups: [
          {
            groupId: 'default-group',
            products: [
              {
                platform: 'Amazon',
                title: `${input.query} - Standard Edition`,
                description: `Best-selling ${input.query} with high durability and standard features.`,
                price: 499,
                productUrl: 'https://amazon.in',
                specifications: 'Standard quality'
              },
              {
                platform: 'Flipkart',
                title: `${input.query} - Premium Pack`,
                description: `Value pack for ${input.query} available now.`,
                price: 450,
                productUrl: 'https://flipkart.com',
                specifications: 'Standard quality'
              }
            ]
          }
        ],
        savingsAdvice: {
          recommendationSummary: "Standard marketplace offers found.",
          bestOfferPlatform: "Flipkart",
          bestOfferProductTitle: `${input.query} - Premium Pack`,
          reasoning: "Best available price currently found in simulation."
        }
      };
    }
  }
);

export async function searchProductNova(query: string): Promise<OrchestratorOutput> {
  return priceNovaOrchestratorFlow({ query });
}
